#!/usr/bin/env bash

set -e

f=$(mktemp)
cat > "$f" << EOF
[Desktop Entry]
Type=Application
Name=${OVE_DISTROCHECK_CONTAINER_NAME:?}
Exec=xfce4-terminal --fullscreen -e "bash -c 'cd $OVE_BASE_DIR; source ove; ove distcheck dg'"
Terminal=false
EOF

ove echo cyan "create .config/autostart"
ssh "${OVE_DISTROCHECK_CONTAINER_NAME:?}" "mkdir -pv .config/autostart"

ove echo cyan "create autostart file"
scp -q "$f" "${OVE_DISTROCHECK_CONTAINER_NAME:?}":.config/autostart/"${OVE_DISTROCHECK_CONTAINER_NAME:?}".desktop

rm "$f"

ove echo cyan "restart ${OVE_DISTROCHECK_CONTAINER_NAME:?} container"
incus restart "${OVE_DISTROCHECK_CONTAINER_NAME:?}"
